//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UETV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_sensor_analytics
    {
        public int id { get; set; }
        public double value { get; set; }
        public System.DateTime creationTime { get; set; }
        public Nullable<int> sensor_id { get; set; }
    
        public virtual acc_sensors acc_sensors { get; set; }
    }
}
