//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UETV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_sensors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_sensors()
        {
            this.acc_sensor_analytics = new HashSet<acc_sensor_analytics>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> lng { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<int> max_value { get; set; }
        public Nullable<int> min_value { get; set; }
        public Nullable<double> lastValue { get; set; }
        public string lastUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_sensor_analytics> acc_sensor_analytics { get; set; }
    }
}
