//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UETV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class getsensorsanalyticsview
    {
        public Nullable<long> id { get; set; }
        public Nullable<int> parentId { get; set; }
        public string sensorName { get; set; }
        public string sensorImage { get; set; }
        public Nullable<long> creatorId { get; set; }
        public Nullable<System.DateTime> creationTime { get; set; }
        public string sensorCurrentValue { get; set; }
        public string sensorNormalValue { get; set; }
        public Nullable<double> sensorMaxValue { get; set; }
        public Nullable<double> sensorMinValue { get; set; }
        public long numerOfRecords { get; set; }
    }
}
